# Generated by Django 3.0.4 on 2020-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Fruits and Vegetables', 'Fruits and Vegetables'), ('Medicine', 'Medicine'), ('Meat and Fish', 'Meat and Fish')], max_length=50)),
                ('image_url', models.CharField(max_length=2048, null=True)),
                ('in_stock', models.BooleanField(null=True)),
            ],
        ),
    ]
