# Generated by Django 3.0.4 on 2020-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fruits and Vegetables', 'Fruits and Vegetables'), ('Medicine', 'Medicine'), ('Meat and Fish', 'Meat and Fish'), ('Electronics', 'Electronics'), ('Stationary', 'Stationary'), ('Grocery', 'Grocery'), ('Pet Foods', 'Pet Foods')], max_length=100)),
                ('openstatus', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('image_url', models.CharField(max_length=2048, null=True)),
            ],
        ),
    ]
